type DataListNFTOwnerProps = {
  key: number | string;
  id: number | string;
  email: string;
  userName: string;
  idNFT: string;
  NFTName: string;
  NFTType: string;
  NFTImage?: string;
  aquistionDate: string;
  transactionDate: string;
  transactionStatus: string;
  actions?: string;
};
export const dataListNFTOwnerSource: DataListNFTOwnerProps[] = [
  {
    key: '1',
    id: 1,
    email: 'testmail@gmail.com',
    userName: 'Khánh',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Active',
  },
  {
    key: '2',
    id: '2',
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Transferred',
    actions: 'Update',
  },
  {
    key: '3',
    id: 3,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    actions: 'Update',
  },
  {
    key: '4',
    id: 4,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Sold',
    // actions: 'Update',
  },
  {
    key: '5',
    id: 5,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Active',
    // actions: 'Update',
  },
  {
    key: '1',
    id: 6,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'In Transaction',
  },
  {
    key: '7',
    id: 7,
    email: 'testmail@gmail.com',
    userName: 'Mike',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'In Transaction',
    // actions: 'Update',
  },
  {
    key: '8',
    id: 8,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'In Transaction',
    // actions: 'Update',
  },
  {
    key: '9',
    id: 9,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Transferred',
    // actions: 'Update',
  },
  {
    key: '10',
    id: 10,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Transferred',
    // actions: 'Update',
  },
  {
    key: '11',
    id: 11,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Transferred',
    // actions: 'Update',
  },
  {
    key: '12',
    id: 12,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Transferred',
    // actions: 'Update',
  },
  {
    key: '13',
    id: 13,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Transferred',
    // actions: 'Update',
  },
  {
    key: '14',
    id: 14,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    // actions: 'Update',
  },
  {
    key: '15',
    id: 15,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    // actions: 'Update',
  },
  {
    key: '15',
    id: 16,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    // actions: 'Update',
  },
  {
    key: '17',
    id: 17,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    // actions: 'Update',
  },
  {
    key: '18',
    id: 18,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    // actions: 'Loser',
  },
  {
    key: '19',
    id: 19,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    // actions: 'Update',
  },
  {
    key: '20',
    id: 20,
    email: 'testmail@gmail.com',
    userName: 'John',
    idNFT: 'NFT 1234',
    NFTName: 'Binance',
    NFTType: 'artwork',
    NFTImage: 'https://picsum.photos/800/600',
    aquistionDate: '2024, Sep 27',
    transactionDate: '2024, Sep 02',
    transactionStatus: 'Pending',
    // actions: 'Update',
  },
];
