type DataUserSourceItem = {
  key: string;
  id: number | string;
  username: string;
  email: string;
  createdDate: string;
  status: string;
  accounttype?: string;
  actions: string;
};
export const dataUserSource: DataUserSourceItem[] = [
  {
    key: '1',
    id: 1,
    username: 'Mike',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Open',
    accounttype: 'admin',
    actions: 'Update',
  },
  {
    key: '2',
    id: '2',
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Close',
    accounttype: 'admin',
    actions: 'Update',
  },
  {
    key: '3',
    id: 3,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Verified',
    accounttype: 'operators',
    actions: 'Update',
  },
  {
    key: '4',
    id: 4,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Unverified',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '5',
    id: 5,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Open',
    accounttype: 'operators',
    actions: 'Update',
  },
  {
    key: '6',
    id: 6,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    accounttype: 'operators',
    actions: 'Update',
  },
  {
    key: '7',
    id: 7,
    username: 'Mike',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Open',
    accounttype: 'admin',
    actions: 'Update',
  },
  {
    key: '8',
    id: 8,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Close',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '9',
    id: 9,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Close',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '10',
    id: 10,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Verifiled',
    accounttype: 'operators',
    actions: 'Update',
  },
  {
    key: '11',
    id: 11,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    accounttype: 'operators',
    actions: 'Update',
  },
  {
    key: '12',
    id: 12,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Close',
    accounttype: 'admin',
    actions: 'Update',
  },
  {
    key: '13',
    id: 13,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Unverified',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '14',
    id: 14,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Close',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '15',
    id: 15,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Open',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '16',
    id: 16,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Close',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '17',
    id: 17,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '18',
    id: 18,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Open',
    accounttype: 'user',
    actions: 'Loser',
  },
  {
    key: '19',
    id: 19,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    accounttype: 'user',
    actions: 'Update',
  },
  {
    key: '20',
    id: 20,
    username: 'John',
    email: 'testdemo@gmail.com',
    createdDate: '2024, Sep 02',
    status: 'Close',
    accounttype: 'user',
    actions: 'Update',
  },
];
