type DataSourceItem = {
  key: string;
  id: number | string;
  collectionsName: string;
  publisher: string;
  NFTImage?: string;
  createdDate: string;
  status: 'Open' | 'Close' | 'Pending';
  actions: string;
};
export const dataSource: DataSourceItem[] = [
  {
    key: '1',
    id: 1,
    collectionsName: 'Mike',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '2',
    id: '2',
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '3',
    id: 3,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Update',
  },
  {
    key: '4',
    id: 4,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '5',
    id: 5,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Update',
  },
  {
    key: '6',
    id: 6,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '7',
    id: 7,
    collectionsName: 'Mike',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Update',
  },
  {
    key: '8',
    id: 8,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '9',
    id: 9,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '10',
    id: 10,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '11',
    id: 11,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '12',
    id: 12,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '13',
    id: 13,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Update',
  },
  {
    key: '14',
    id: 14,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '15',
    id: 15,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Update',
  },
  {
    key: '16',
    id: 16,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '17',
    id: 17,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '18',
    id: 18,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Loser',
  },
  {
    key: '19',
    id: 19,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '20',
    id: 20,
    collectionsName: 'John',
    publisher: 'JRE Team',
    NFTImage: 'https://picsum.photos/800/600',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
];
