type DataWalletSourceProps = {
  key: number | string;
  id: number | string;
  userName: string;
  email: string;
  walletAddress: string;
  walletType: string;
  createdDate: string;
  status: string;
  actions: string;
};
export const dataWalletSource: DataWalletSourceProps[] = [
  {
    key: '1',
    id: 1,
    userName: 'Khánh',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Open',

    actions: 'Update',
  },
  {
    key: '2',
    id: '2',
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'Suica',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '3',
    id: 3,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Verified',
    actions: 'Update',
  },
  {
    key: '4',
    id: 4,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'Suica',
    createdDate: '2024, Sep 02',
    status: 'Unverified',
    actions: 'Update',
  },
  {
    key: '5',
    id: 5,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'Suica',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Update',
  },
  {
    key: '1',
    id: 6,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '7',
    id: 7,
    userName: 'Mike',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Open',

    actions: 'Update',
  },
  {
    key: '8',
    id: 8,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '9',
    id: 9,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'Suica',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '10',
    id: 10,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'Suica',
    createdDate: '2024, Sep 02',
    status: 'Verifiled',
    actions: 'Update',
  },
  {
    key: '11',
    id: 11,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '12',
    id: 12,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Close',

    actions: 'Update',
  },
  {
    key: '13',
    id: 13,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Unverified',
    actions: 'Update',
  },
  {
    key: '14',
    id: 14,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '15',
    id: 15,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Update',
  },
  {
    key: '15',
    id: 16,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
  {
    key: '17',
    id: 17,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '18',
    id: 18,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Open',
    actions: 'Loser',
  },
  {
    key: '19',
    id: 19,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Pending',
    actions: 'Update',
  },
  {
    key: '20',
    id: 20,
    userName: 'John',
    email: 'testdemo@gmail.com',
    walletAddress: '0x0jdhdhha101iwuf2or00102jqjwf',
    walletType: 'no suica',
    createdDate: '2024, Sep 02',
    status: 'Close',
    actions: 'Update',
  },
];
